### ISSUE TITLE
systemctl monitoring: regex issue

### ISSUE THREAD

**Issue by wrighterase** [catonrug/zabbix_agentd.d#3]
the value map in your demo did not work even while running the same version of Zabbix that was demoed. the following solution did work on 4.2.5 and 4.4.5
^(dead|running|exited|start).*(?=(\1=(\d))) and matching on \3

**Comment by catonrug** [comment]
Thank you for using GitHub platform to report bugs.
However, the RegEx formula in your example differs from the one in the template. 
In the template it's configured like:
![image](https://user-images.githubusercontent.com/6340467/74587244-e030ce00-4ff8-11ea-94f5-2737d79fd593.png)
At the last step, we are extracting group 2.

Please try to apply the template:
https://raw.githubusercontent.com/catonrug/zabbix_agentd.d/master/service_monitoring_via_systemctl.xml

**Comment by wrighterase** [comment]
thanks.  i did apply the template, but it was applied on version 4.0.  due to the feature difference in versions i think the template did not import fully and i used the youtube video to try and match the preprocessing rules.  apologies for the non-issue.
